import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/providers/items_provider.dart'; 
import '../../../../core/models/category_model.dart';

class AdminCategoriesScreen extends ConsumerWidget {
  const AdminCategoriesScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: const Text('Manage Categories')),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddDialog(context, ref),
        child: const Icon(Icons.add),
      ),
      body: FutureBuilder<List<CategoryModel>>(
        future: ref.read(firestoreServiceProvider).getCategories(), // Should convert this to stream if dynamic updates needed
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) return const Center(child: CircularProgressIndicator());
          
          final categories = snapshot.data ?? [];
          
          return ListView.builder(
            itemCount: categories.length,
            itemBuilder: (context, index) {
              final cat = categories[index];
              return ListTile(
                leading: const Icon(Icons.category),
                title: Text(cat.name),
                subtitle: Text(cat.description ?? ''),
                trailing: IconButton(
                  icon: const Icon(Icons.delete, color: Colors.red),
                  onPressed: () => _deleteCategory(context, ref, cat.id),
                ),
              );
            },
          );
        },
      ),
    );
  }

  Future<void> _showAddDialog(BuildContext context, WidgetRef ref) async {
    final nameCtrl = TextEditingController();
    final descCtrl = TextEditingController();
    
    await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add Category'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(controller: nameCtrl, decoration: const InputDecoration(labelText: 'Name')),
            TextField(controller: descCtrl, decoration: const InputDecoration(labelText: 'Description')),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          TextButton(
            onPressed: () async {
              if (nameCtrl.text.isNotEmpty) {
                 final cat = CategoryModel(
                   id: '', // Generated by Firestore if using .add() but .add() returns ref, we might not set ID in object before sending?
                   // Actually FirestoreService.addCategory uses .add(category.toFirestore()). The ID in model is ignored or empty.
                   name: nameCtrl.text,
                   iconUrl: '', // Mock or add picker
                   description: descCtrl.text,
                   isActive: true,
                   displayOrder: 0,
                 );
                 await ref.read(firestoreServiceProvider).addCategory(cat);
                 Navigator.pop(context);
                 // Force refresh? The FutureBuilder won't auto-refresh. Ideally use Stream.
                 // For now, simple UI.
              }
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }

  Future<void> _deleteCategory(BuildContext context, WidgetRef ref, String id) async {
     await ref.read(firestoreServiceProvider).deleteCategory(id);
     // Trigger rebuild?
  }
}
